version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: kungnection-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: kungnection
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  backend:
    build: .
    container_name: kungnection-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/kungnection
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    restart: always
    # Uncomment if you want to wait for db to be ready (optional)
    # entrypoint: ["/bin/sh", "-c", "./wait-for-it.sh db:3306 -- java -jar app.jar"]

volumes:
  db_data:
